# Generated by Django 2.0.2 on 2018-02-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listemail',
            old_name='emails',
            new_name='email',
        ),
    ]
